# Week 1 Student Performance Dataset Analysis

AI&ML Internship – WeIntern Pvt Ltd

Name: Yogesh Negi

In [13]:
import pandas as pd

In [12]:
df = pd.read_csv("StudentsPerformance.csv")

In [ ]:
df.head()

,Student ID,Gender,Age,Attendance Percentage,Study Hours Per Week,Assignment Score,Midterm Score,Final Score,Parental Education,Internet Access,Extra Activities
0,S0064,F,18,92.8,NaN,46.7,NaN,72.3,NaN,YES,N
1,S0061,NaN,18,49.9,1.0,34.3,26.9,38.9,Bachelor's Degree,Yes,No
2,S0005,NaN,19,83.0,17.9,54.3,95.5,51.7,phd,Yes,N
3,S0097,Male,15,55.5,10.8,81.8,82.1,61.3,Associate Degree,No,NO
4,S0177,NaN,21,53.4,16.8,79.4,58.2,56.8,High School,NO,yes

In [ ]:
df.tail()

,Student ID,Gender,Age,Attendance Percentage,Study Hours Per Week,Assignment Score,Midterm Score,Final Score,Parental Education,Internet Access,Extra Activities
201,S0070,male,21,98.9,13.0,96.1,34.5,69.6,phd,NO,Yes
202,S0131,M,17,72.8,19.4,74.6,65.8,105.0,High School,No,NO
203,S0081,female,22,81.6,11.1,81.9,57.9,91.2,masters,Yes,YES
204,S0155,male,18,64.1,19.6,95.6,71.8,34.2,masters,YES,no
205,S0198,M,20,76.1,7.8,98.6,91.4,90.7,Associate Degree,YES,Y

In [25]:
#Dataset Shape
print("Rows and Columns:", df.shape)

Rows and Columns: (200, 11)

In [14]:
#Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student ID             206 non-null    object
 1   Gender                 193 non-null    object
 2   Age                    206 non-null    int64
 3   Attendance Percentage  194 non-null    float64
 4   Study Hours Per Week   189 non-null    float64
 5   Assignment Score       206 non-null    float64
 6   Midterm Score          199 non-null    float64
 7   Final Score            206 non-null    float64
 8   Parental Education     162 non-null    object
 9   Internet Access        192 non-null    object
 10  Extra Activities       206 non-null    object
dtypes: float64(5), int64(1), object(5)
memory usage: 17.8+ KB

Feature Understanding Table


| Feature               | Type        | Description                 |
| --------------------- | ----------- | --------------------------- |
| Student ID            | Identifier  | Unique student ID           |
| Gender                | Categorical | Student gender              |
| Age                   | Numerical   | Student age                 |
| Attendance Percentage | Numerical   | Attendance percentage       |
| Study Hours Per Week  | Numerical   | Weekly study hours          |
| Assignment Score      | Numerical   | Assignment marks            |
| Midterm Score         | Numerical   | Midterm marks               |
| Final Score           | Numerical   | Final examination marks     |
| Parental Education    | Categorical | Parent education level      |
| Internet Access       | Categorical | Internet availability       |
| Extra Activities      | Categorical | Participation in activities |

In [ ]:
#missing values
df.isnull().sum()

Student ID                0
Gender                   13
Age                       0
Attendance Percentage    12
Study Hours Per Week     17
Assignment Score          0
Midterm Score             7
Final Score               0
Parental Education       44
Internet Access          14
Extra Activities          0
dtype: int64

In [ ]:
# Check for duplicated rows
print('Number of duplicated rows:', df.duplicated().sum())

Number of duplicated rows: 6

Cleaning Dataset

In [26]:
#Remove duplicates
df = df.drop_duplicates()

In [17]:
#Fill Gender
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [18]:
#Fill Attendance
df["Attendance Percentage"] = df["Attendance Percentage"].fillna(
    df["Attendance Percentage"].median()
)

In [19]:
#Fill Study Hours
df["Study Hours Per Week"] = df["Study Hours Per Week"].fillna(
    df["Study Hours Per Week"].median()
)

In [20]:
#Fill Midterm Score
df["Midterm Score"] = df["Midterm Score"].fillna(
    df["Midterm Score"].median()
)

In [21]:
#Fill Parental Education
df["Parental Education"] = df["Parental Education"].fillna(
    df["Parental Education"].mode()[0]
)

In [22]:
#Fill Internet Access
df["Internet Access"] = df["Internet Access"].fillna(
    df["Internet Access"].mode()[0]
)

In [23]:
#Cleaned dataset
df.isnull().sum()

Student ID               0
Gender                   0
Age                      0
Attendance Percentage    0
Study Hours Per Week     0
Assignment Score         0
Midterm Score            0
Final Score              0
Parental Education       0
Internet Access          0
Extra Activities         0
dtype: int64

All values are now showing 0.

In [27]:
df.to_csv("cleaned_student_performance.csv", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully